site_name: "T-SQL Tutorial"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
  icon:
    logo: material/book-open-variant-outline
    favicon: assets/images/favicon.webppng

nav:
  - Foundations & Setup:
      - 001. History of SQL to Modern T-SQL: 001_History_of_SQL_to_modern_T_SQL.md
      - 002. Getting Started: 002_Getting_Started.md
      - 003. Installation: 003_Installation.md
      - 004. SQL Server Management Studio (SSMS) Walkthrough: 004_SQL_Server_Management_Studio_SSMS_Walkthrough.md

  - Core T-SQL Language:
      - 005. T-SQL DDL (Data Definition Language) Commands: 005_T_SQL_DDL_Data_Definition_Language_Commands.md
      - 006. T-SQL DML (Data Manipulation Language) Commands: 006_T_SQL_DML_Data_Manipulation_Language_Commands.md
      - 007. T-SQL DQL (Data Query Language) Commands: 007_T_SQL_DQL_Data_Query_Language_Commands.md
      - 008. T-SQL TCL (Transaction Control Language) Commands: 008_T_SQL_TCL_Transaction_Control_Language_Commands.md
      - 009. T-SQL DCL (Data Control Language) Commands: 009_T_SQL_DCL_Data_Control_Language_Commands.md

  - Advanced Topics:
      - 010. Indexing in T-SQL: 010_Indexing_in_T_SQL.md
      - 011. T-SQL Practice Problems: 011_T_SQL_Practice_Problems.md
      - 012. Frequently Asked Questions: 012_Frequently_Asked_Questions.md

plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: "&copy;2024 Searchspring. All rights reserved."
